/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.ui;

import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import edu.neu.csye6200.controller.DayCareCompany;
import edu.neu.csye6200.model.ImmunizationRule;

/**
 *
 * @author hairihan
 */
public class AddImmunizationRuleJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form AddImmunizationRuleJPanel
	 */
	private DayCareCompany d;
	private ImmunizationRulesJPanel i;
	private JFrame f;
	private DefaultTableModel t;
	
	public AddImmunizationRuleJPanel(DayCareCompany d, ImmunizationRulesJPanel i, JFrame f, DefaultTableModel t) {
		// TODO Auto-generated constructor stub
		this.d = d;
		this.i= i;
		this.f=f;
		this.t=t;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		txtImmunizationID = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txtAgeFrom = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtRequiredAmount = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		txtAgeTo = new javax.swing.JTextField();
		btnSubmit = new javax.swing.JButton();

		jLabel2.setBackground(new java.awt.Color(51, 0, 153));
		jLabel2.setFont(new java.awt.Font("Snell Roundhand", 1, 36)); // NOI18N
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("Add Immunization Rule");

		jLabel1.setText("Immunization ID:");

		jLabel3.setText("Age:");

		jLabel4.setText("Required Amount:");

		jLabel5.setText("From:");

		jLabel6.setText("to");

		btnSubmit.setText("Submit");
		btnSubmit.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSubmitActionPerformed(evt);
				
			}
		});
		/*
		
		 */

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(107, 107, 107)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel2)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(55, 55, 55).addComponent(txtImmunizationID,
												javax.swing.GroupLayout.PREFERRED_SIZE, 172,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(41, 41, 41)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtAgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(0, 0, Short.MAX_VALUE)))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE,
																36, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtAgeTo, javax.swing.GroupLayout.PREFERRED_SIZE,
																59, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(txtRequiredAmount, javax.swing.GroupLayout.PREFERRED_SIZE,
														172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
				.addContainerGap(174, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(172, 172, 172)
						.addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 193,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(45, 45, 45).addComponent(jLabel2).addGap(39, 39, 39)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(txtImmunizationID, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addComponent(
						jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(17, 17, 17)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(txtAgeTo, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(txtAgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(48, 48, 48)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(txtRequiredAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(71, 71, 71).addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(78, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void btnSubmitActionPerformed(ActionEvent evt) {
		int id = Integer.parseInt(txtImmunizationID.getText());
		int age1 = Integer.parseInt(txtAgeFrom.getText());
		int age2 = Integer.parseInt(txtAgeTo.getText());
		int re = Integer.parseInt(txtRequiredAmount.getText());
		String descr = "New Rule";
		for (ImmunizationRule x : d.getImmunizationRules()) {
			if (x.getRuleID() == id) {
				descr = x.getImmunization();
			}
		}
		ImmunizationRule r = new ImmunizationRule(id, age1, age2, descr, re);
		d.addImmunizationRule(r);
		try {
			d.getWriter().writeImmunizationRuleData();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		f.setVisible(false);
		f.dispose();

		
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSubmit;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField txtAgeFrom;
	private javax.swing.JTextField txtAgeTo;
	private javax.swing.JTextField txtImmunizationID;
	private javax.swing.JTextField txtRequiredAmount;
	// End of variables declaration//GEN-END:variables
}
