/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.ui;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import edu.neu.csye6200.controller.DayCareCompany;
import edu.neu.csye6200.model.ClassRoom;

/**
 *
 * @author hairihan
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */

	
	private DayCareCompany company;
	 private JPanel userProcessContainer;
	 private int classNo=-1;
	
    public AdminJPanel(DayCareCompany d,JPanel userProcessContainer) {
    	this.company=d;
    	this.userProcessContainer=userProcessContainer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	classNo=-1;
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();
        btnViewRules = new javax.swing.JButton();
        btnViewRules.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				JFrame f = new JFrame();
				f.setBounds(0, 0,1248,794);
				ImmunizationRulesJPanel i = new ImmunizationRulesJPanel(company,f);
				i.setVisible(true);
	            f.add(i);
	            f.setVisible(true);
			}
		});

        setBackground(new java.awt.Color(51, 0, 153));

        
        DefaultTableModel table = new DefaultTableModel();
        String [] colTitles = {"Class ID", "Student Amount", "Teacher Amount"};
        table.setColumnCount(colTitles.length);
        table.setColumnIdentifiers(colTitles);
    	for(ClassRoom c:company.getClassRooms()) {
    		table.addRow(new Object[]{c.getClassRoomID(),c.getNumberOfStudents(),c.getTeachers().size()});
    	}
    	
        jTable1.setModel(table);
		jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent event) {
				System.out.println("Selected " + table.getValueAt(jTable1.getSelectedRow(), 0).toString());
				int id = Integer.parseInt(table.getValueAt(jTable1.getSelectedRow(), 0).toString());
				classNo = id;
			}
		});
        
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Snell Roundhand", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrator");

        btnDetails.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btnDetails.setForeground(new java.awt.Color(51, 0, 153));
        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDetailsActionPerformed(evt);
			}
		});


        btnViewRules.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        btnViewRules.setForeground(new java.awt.Color(51, 0, 153));
        btnViewRules.setText("View Rules");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewRules, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewRules, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    protected void btnDetailsActionPerformed(ActionEvent evt) {
    	if(classNo==-1) {
    		JOptionPane.showMessageDialog(null, "Please select a class");
    	}
    	else {
	    	AdminDetailsJPanel panel = new AdminDetailsJPanel(company, userProcessContainer,classNo);
			userProcessContainer.add("AdminDetailsJPanel", panel);
			CardLayout layout = (CardLayout) userProcessContainer.getLayout();
			layout.next(userProcessContainer);
    	}
	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnViewRules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
