/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

import edu.neu.csye6200.controller.DayCareCompany;
import edu.neu.csye6200.model.Immunization;
import edu.neu.csye6200.model.ImmunizationRule;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hairihan
 */
public class ImmunizationRulesJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ImmunizationRulesJPanel
	 */
	private DayCareCompany d;
	private JFrame frame;
	private DefaultTableModel t;
	private int selectedID = -1;
	private int selectedAge1 = -1;
	private int selectedAge2 = -1;

	public ImmunizationRulesJPanel(DayCareCompany d, JFrame f) {
		this.d = d;
		this.frame = f;
		initComponents();
	}

	public int getSelectedID() {
		return selectedID;
	}

	public void setSelectedID(int selectedID) {
		this.selectedID = selectedID;
	}

	public int getSelectedAge1() {
		return selectedAge1;
	}

	public void setSelectedAge1(int selectedAge1) {
		this.selectedAge1 = selectedAge1;
	}

	public int getSelectedAge2() {
		return selectedAge2;
	}

	public void setSelectedAge2(int selectedAge2) {
		this.selectedAge2 = selectedAge2;
	}

	public boolean notSelected() {
		return (selectedAge1 == -1 && selectedAge2 == -1 && selectedID == -1);
	}

	public void setUnselected() {
		selectedAge1 = -1;
		selectedAge2 = -1;
		selectedID = -1;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		btnAddRole = new javax.swing.JButton();
		btnEditRule = new javax.swing.JButton();
		btnDeleteRule = new javax.swing.JButton();

	//	jLabel2.setBackground(new java.awt.Color(255,255,255));
		  jLabel2.setBackground(new java.awt.Color(51, 0, 153));
		jLabel2.setFont(new java.awt.Font("Garamond", 1, 30)); // NOI18N
		//jPanel1.setBackground(new java.awt.Color(20,61,89));
//		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("Immunization Rules");
		jLabel2.setForeground(new java.awt.Color(255,255,255));

		DefaultTableModel table = new DefaultTableModel();
		String[] colTitles = { "Immunization ID", "Immunization Name", "Age Range", "Required Amount" };
		table.setColumnCount(colTitles.length);
		table.setColumnIdentifiers(colTitles);
		


		for (ImmunizationRule i : d.getImmunizationRules()) {
			table.addRow(new Object[] { i.getRuleID(), i.getImmunization(),
					i.getAgeLowerLimit() + "-" + i.getAgeUpperLimit(), i.getRequiredAmt() });
		}
		setBackground(new java.awt.Color(20,61,89));

		jTable1.setModel(table);

		// select a row
		jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent event) {
				// do some actions here, for example
				// print first column value from selected row
				System.out.println("Selected " + table.getValueAt(jTable1.getSelectedRow(), 0).toString());
				int id = Integer.parseInt(table.getValueAt(jTable1.getSelectedRow(), 0).toString());
				String range = (table.getValueAt(jTable1.getSelectedRow(), 2).toString());
				int age1 = Integer.parseInt(range.split("-")[0]);
				int age2 = Integer.parseInt(range.split("-")[1]);
				selectedAge1 = age1;
				selectedAge2 = age2;
				selectedID = id;
			}
		});
		this.t = table;

		jScrollPane1.setViewportView(jTable1);
	//	setBackground(new java.awt.Color(255,255,255));

		btnAddRole.setText("Add Rule");
		//btnAddRole.setBackground(new java.awt.Color(255,255,255));
		btnAddRole.setForeground(new java.awt.Color(20,61,89));
		btnAddRole.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
		//  jLabel2.setBackground(new java.awt.Color(51, 0, 153));
		btnAddRole.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddRoleActionPerformed(evt);
			}
		});

		btnEditRule.setText("Confirm Update");
		//btnEditRule.setBackground(new java.awt.Color(255,255,255));
		btnEditRule.setForeground(new java.awt.Color(20,61,89));
		btnEditRule.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
		btnEditRule.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEditRuleActionPerformed(evt);
			}
		});

		btnDeleteRule.setText("Delete Rule");
		//btnDeleteRule.setBackground(new java.awt.Color(255,255,255));
		btnDeleteRule.setForeground(new java.awt.Color(20,61,89));
		btnDeleteRule.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
		btnDeleteRule.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (notSelected()) {
					// pop up warning window
					System.out.println("No rule is selected");
				} else {
					ImmunizationRule remove = null;
					for (ImmunizationRule r : d.getImmunizationRules()) {
						if (r.getRuleID() == selectedID && r.getAgeLowerLimit() == selectedAge1
								&& r.getAgeUpperLimit() == selectedAge2) {
							remove = r;
						}
					}

					if (remove == null) {
						System.out.println("Cannot locate the rule for removal");
						
					} else {
						d.getImmunizationRules().remove(remove);
						try {
							d.getWriter().writeImmunizationRuleData();
							System.out.println("Remove rule successfully");
							JOptionPane.showMessageDialog(null, "Rule Deleted Successfully");
							frame.setVisible(false);
							frame.dispose();
						} catch (IOException e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
						
					}
				}
				

			}
			
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(480, 480, 480).addComponent(jLabel2))
						.addGroup(layout.createSequentialGroup().addGap(400, 400, 400).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup().addComponent(btnAddRole).addGap(88, 88, 88)
										.addComponent(btnEditRule).addGap(546, 546, 546).addComponent(btnDeleteRule)))))
				.addContainerGap(217, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(83, 83, 83).addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnAddRole, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEditRule, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnDeleteRule, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(123, 123, 123)));
	}// </editor-fold>//GEN-END:initComponents

	private void btnEditRuleActionPerformed(ActionEvent evt) {
//{"Immunization ID", "Immunization Name", "Age Range", "Required Amount"};
		int col = t.getColumnCount() - 1;
		String change = "Nothing changed";
		for (int row = 1; row < t.getRowCount(); row++) {
			String val = (t.getValueAt(row, col).toString());
			if (d.getImmunizationRules().get(row).getRequiredAmt() != Integer.parseInt(val)) {
				System.out.println(row + ":" + col + "=" + val);
				d.getImmunizationRules().get(row).setRequiredAmt(Integer.parseInt(val));
				change = "Changes are made successfully";
				try {
					d.getWriter().writeImmunizationRuleData();
				//	t.fireTableDataChanged();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}

		}
		JOptionPane.showMessageDialog(this, change);
		 initComponents();
		

	}

	private void btnAddRoleActionPerformed(java.awt.event.ActionEvent e) {// GEN-FIRST:event_btnAddRoleActionPerformed
		// TODO add your handling code here:

		JFrame f = new JFrame();
		f.setBounds(0, 0, 1248, 794);
		AddImmunizationRuleJPanel add = new AddImmunizationRuleJPanel(d, this, f, t);
		add.setVisible(true);
		f.add(add);
		f.setVisible(true);
	
		this.frame.setVisible(false);
		this.frame.dispose();
	}// GEN-LAST:event_btnAddRoleActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAddRole;
	private javax.swing.JButton btnDeleteRule;
	private javax.swing.JButton btnEditRule;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables
}
