/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.ui;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JPanel;

import edu.neu.csye6200.controller.DataLoader;
import edu.neu.csye6200.controller.DataWriter;
import edu.neu.csye6200.controller.DayCareCompany;
import edu.neu.csye6200.model.ClassRoomRule;

/**
 *
 * @author hairihan
 */
public class MainJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form MainJFrame
	 */
	private DayCareCompany d;

	public MainJFrame(DayCareCompany d) {
		this.d = d;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSplitPane1 = new javax.swing.JSplitPane();
		jPanel1 = new javax.swing.JPanel();
		btn_Admin = new javax.swing.JButton();
		btn_Student = new javax.swing.JButton();
		btn_Teacher = new javax.swing.JButton();
		btn_Exit = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		userProcessContainer = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(800, 550));

		jPanel1.setBackground(new java.awt.Color(20,61,89));

		btn_Admin.setBackground(new java.awt.Color(255, 255, 255));
		btn_Admin.setFont(new java.awt.Font("Garamond", 1, 19)); // NOI18N
		btn_Admin.setForeground(new java.awt.Color(20,61,89));
		btn_Admin.setText("Admin");
		btn_Admin.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				//AdminJPanel a = new AdminJPanel(d, userProcessContainer);
				AdminJPanel panel = new AdminJPanel(d, userProcessContainer);
				userProcessContainer.add("AdminJPanel", panel);
				CardLayout layout = (CardLayout) userProcessContainer.getLayout();
				layout.next(userProcessContainer);
			}
		});

		btn_Student.setBackground(new java.awt.Color(255, 255, 255));
		btn_Student.setFont(new java.awt.Font("Garamond", 1, 19)); // NOI18N
		btn_Student.setForeground(new java.awt.Color(20,61,89));
		btn_Student.setText("Student");
		btn_Student.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				StudentPanel panel = new StudentPanel(d, userProcessContainer);
				userProcessContainer.add("StudentPanel", panel);
				CardLayout layout = (CardLayout) userProcessContainer.getLayout();
				layout.next(userProcessContainer);
			}
		});

		btn_Teacher.setBackground(new java.awt.Color(255, 255, 255));
		btn_Teacher.setFont(new java.awt.Font("Garamond", 1, 19)); // NOI18N
		btn_Teacher.setForeground(new java.awt.Color(20,61,89));
		btn_Teacher.setText("Teacher");
		btn_Teacher.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				TeacherJPanel panel = new TeacherJPanel(d, userProcessContainer);
				userProcessContainer.add("TeacherPanel", panel);
				CardLayout layout = (CardLayout) userProcessContainer.getLayout();
				layout.next(userProcessContainer);
			}
		});

		btn_Exit.setBackground(new java.awt.Color(255, 255, 255));
		btn_Exit.setFont(new java.awt.Font("Garamond", 1, 19)); // NOI18N
		btn_Exit.setForeground(new java.awt.Color(20,61,89));
		btn_Exit.setText("EXIT");
		btn_Exit.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				setVisible(false);
				dispose();
			}
		});


		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("Menu");
		jLabel3.setFont(new java.awt.Font("Garamond", 1, 30));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				.addComponent(btn_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(btn_Student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(btn_Teacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addGap(31, 31, 31)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btn_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(btn_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(btn_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(91, 91, 91)));

		jSplitPane1.setLeftComponent(jPanel1);
		userProcessContainer.setLayout(new java.awt.CardLayout());
		jSplitPane1.setRightComponent(userProcessContainer);

		userProcessContainer.setBackground(new java.awt.Color(255,255,255));
		userProcessContainer.setLayout(new java.awt.CardLayout());

		userProcessContainer.setBackground(new java.awt.Color(255,255,255));
		userProcessContainer.setFont(new java.awt.Font("Snell Roundhand", 1, 48)); // NOI18N
		userProcessContainer.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("Welcome to DayCare ");
		jLabel2.setFont(new java.awt.Font("Garamond", 1, 50));
		jLabel2.setForeground(new java.awt.Color(20,61,89));
		userProcessContainer.add(jLabel2, "card3");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE));

		pack();

	}// </editor-fold>//GEN-END:initComponents

//	private void btn_AdminActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_AdminActionPerformed
//		// TODO add your handling code here:
//		JFrame f = new JFrame();
//		f.setBounds(0, 0, 1248, 794);
//		AdminJPanel a = new AdminJPanel(d, userProcessContainer);
//		a.setVisible(true);
//		f.add(a);
//		f.setVisible(true);
//	}// GEN-LAST:event_btn_AdminActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		DayCareCompany dayCareCompany = new DayCareCompany();
		dayCareCompany.setW(new DataWriter(dayCareCompany));
		DataLoader loader = new DataLoader(dayCareCompany);
		ClassRoomRule rule1 = new ClassRoomRule(1, "Classroom for ages 6-12", 12, 6, 0.25, 4, 12, 3);
		ClassRoomRule rule2 = new ClassRoomRule(2, "Classroom for ages 13-24", 24, 13, 0.20, 5, 15, 3);
		ClassRoomRule rule3 = new ClassRoomRule(3, "Classroom for ages 25-35", 35, 25, 0.20, 6, 18, 3);
		ClassRoomRule rule4 = new ClassRoomRule(4, "Classroom for ages 36-47", 47, 36, 0.20, 8, 24, 3);
		ClassRoomRule rule5 = new ClassRoomRule(5, "Classroom for ages 48-59", 59, 48, 0.20, 12, 24, 2);
		ClassRoomRule rule6 = new ClassRoomRule(6, "Classroom for ages 60 and above", 24, 60, 0.20, 15, 30, 2);
		dayCareCompany.setClassRuleSet(rule1);
		dayCareCompany.setClassRuleSet(rule2);
		dayCareCompany.setClassRuleSet(rule3);
		dayCareCompany.setClassRuleSet(rule4);
		dayCareCompany.setClassRuleSet(rule5);
		dayCareCompany.setClassRuleSet(rule6);
		loader.readEverything();

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				MainJFrame mainFrame = new MainJFrame(dayCareCompany);
				mainFrame.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_Admin;
	private javax.swing.JButton btn_Student;
	private javax.swing.JButton btn_Teacher;
	private javax.swing.JButton btn_Exit;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JPanel userProcessContainer;
	// End of variables declaration//GEN-END:variables
}
