/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;

import edu.neu.csye6200.controller.DayCareCompany;
import edu.neu.csye6200.model.ClassRoom;
import edu.neu.csye6200.model.Person;
import edu.neu.csye6200.model.Student;
import javax.swing.JOptionPane;

/**
 *
 * @author hairihan
 */
public class StudentJPanel extends javax.swing.JPanel {
	private DayCareCompany d;
    /**
     * Creates new form StudentJPanel
     */
    public StudentJPanel(DayCareCompany d) {
    	this.d=d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 0, 153));

        jLabel1.setBackground(new java.awt.Color(51, 0, 153));
        jLabel1.setFont(new java.awt.Font("Snell Roundhand", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student");

        jLabel2.setBackground(new java.awt.Color(51, 0, 153));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search:");

        jLabel3.setBackground(new java.awt.Color(51, 0, 153));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID:");

        txtStudentID.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtStudentID.setForeground(new java.awt.Color(51, 0, 153));

        btnSearch.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(51, 0, 153));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				String text = txtStudentID.getText();
				Student foundPerson = null;
				try {
				int id = Integer.parseInt(text);
				for(Person s:d.getStudents()) {
					if(s.getId()==id) {
						foundPerson= (Student) s;
					}
				}
				JFrame searchInfoFrame = new JFrame();
				searchInfoFrame.setBounds(0, 0,651,631);
				StudentInfoJPanel AS = new StudentInfoJPanel(d);
				String idString=Integer.toString(foundPerson.getId());
				AS.getTxtStudentID1().setText(idString);
				AS.getTxtFirstname().setText(foundPerson.getFirstName());
				AS.getTxtLastname().setText(foundPerson.getLastName());
				String ageString = Integer.toString(foundPerson.getAge());
				AS.getTxtAge().setText(ageString);
				AS.getTxtFather().setText(foundPerson.getFatherName());
				AS.getTxtMother().setText(foundPerson.getMotherName());
				AS.getTxtClassNumber().setText(getClassRoom(foundPerson));;
				AS.getTxtRegisterDate().setText(foundPerson.ft.format(foundPerson.getDateOfEnrollment()));
		        AS.setVisible(true);
		        searchInfoFrame.add(AS);
		        searchInfoFrame.setVisible(true);
				
				}
				catch(Exception f) {
					System.out.println("Invailid ID entered");
				}
			}
		});
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 177, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(81, 81, 81)
                .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
    
    public String getClassRoom(Student s) {
    	Integer classRoomId = null;
    	List<ClassRoom> classRooms = d.getClassRooms();
    	for(ClassRoom c: classRooms) {
    		List<Person> students = c.getStudents();
    		for(Person student : students) {
    			if(s.getId()==student.getId()) {
    				classRoomId = c.getClassRoomID();
    			}
    		}
    	}	
		return classRoomId.toString();
    }
}
