/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.ui;

import java.awt.CardLayout;
import java.util.ListIterator;

import javax.swing.JFrame;
import javax.swing.JPanel;

import edu.neu.csye6200.controller.DayCareCompany;
import edu.neu.csye6200.model.Person;
import edu.neu.csye6200.model.Student;

/**
 *
 * @author hairihan
 */
public class StudentInfoJPanel extends javax.swing.JPanel {
	private DayCareCompany d;
    private JPanel userProcessContainer;
    /**
     * Creates new form StudentInfoJPanel
     */
    public StudentInfoJPanel(DayCareCompany d) {
    	this.d=d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStudentID3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStudentID1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtClassNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFather = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMother = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRegisterDate = new javax.swing.JTextField();
        btnImmunizationRecord = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(51, 0, 153));
        jLabel1.setFont(new java.awt.Font("Snell Roundhand", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student");

        jLabel3.setBackground(new java.awt.Color(51, 0, 153));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID:");

        txtStudentID.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtStudentID.setForeground(new java.awt.Color(51, 0, 153));

        jLabel6.setBackground(new java.awt.Color(51, 0, 153));
        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student ID:");

        txtStudentID3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtStudentID3.setForeground(new java.awt.Color(51, 0, 153));

        setBackground(new java.awt.Color(51, 0, 153));

        jLabel2.setBackground(new java.awt.Color(51, 0, 153));
        jLabel2.setFont(new java.awt.Font("Snell Roundhand", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Information");

        jLabel4.setBackground(new java.awt.Color(51, 0, 153));
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student ID:");

        txtStudentID1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtStudentID1.setForeground(new java.awt.Color(51, 0, 153));
        txtStudentID1.setEditable(false);
        txtStudentID1.setEnabled(false);

        jLabel5.setBackground(new java.awt.Color(51, 0, 153));
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Firstname:");

        txtFirstname.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtFirstname.setForeground(new java.awt.Color(51, 0, 153));
        txtFirstname.setEnabled(false);

        jLabel7.setBackground(new java.awt.Color(51, 0, 153));
        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Lastname:");

        txtLastname.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtLastname.setForeground(new java.awt.Color(51, 0, 153));
        txtLastname.setEnabled(false);

        jLabel8.setBackground(new java.awt.Color(51, 0, 153));
        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Age:");

        txtAge.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(51, 0, 153));
        txtAge.setEnabled(false);

        jLabel9.setBackground(new java.awt.Color(51, 0, 153));
        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Class Number:");

        txtClassNumber.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtClassNumber.setForeground(new java.awt.Color(51, 0, 153));
        txtClassNumber.setEnabled(false);

        jLabel10.setBackground(new java.awt.Color(51, 0, 153));
        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Father:");

        txtFather.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtFather.setForeground(new java.awt.Color(51, 0, 153));
        txtFather.setEnabled(false);

        jLabel11.setBackground(new java.awt.Color(51, 0, 153));
        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Mother:");

        txtMother.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtMother.setForeground(new java.awt.Color(51, 0, 153));
        txtMother.setEnabled(false);

        jLabel12.setBackground(new java.awt.Color(51, 0, 153));
        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Register Date:");

        txtRegisterDate.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtRegisterDate.setForeground(new java.awt.Color(51, 0, 153));
        txtRegisterDate.setEnabled(false);

        btnImmunizationRecord.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnImmunizationRecord.setForeground(new java.awt.Color(51, 0, 153));
        btnImmunizationRecord.setText("Show Immunization Record");
        btnImmunizationRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        
        setBackground(new java.awt.Color(20,61,89));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(59, 59, 59)
                .addComponent(btnImmunizationRecord,  javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(81, 81, 81)
                                .addComponent(txtRegisterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(81, 81, 81)
                                .addComponent(txtMother, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(81, 81, 81)
                                .addComponent(txtFather, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(81, 81, 81)
                                .addComponent(txtClassNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(81, 81, 81)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(81, 81, 81)
                                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(81, 81, 81)
                                .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(81, 81, 81)
                                .addComponent(txtStudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtClassNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRegisterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImmunizationRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
        // TODO add your handling code here:
    	String text = txtStudentID1.getText();
		Student foundPerson = null;
		ListIterator<Person> iterator = d.getStudents().listIterator();
		try {
		int id = Integer.parseInt(text);
		for(Person p : d.getStudents()) {
			if(p.getId()== id) {
				foundPerson = (Student) p;
			}
		}
		
		JFrame addImmunizationRecordFrame = new JFrame();
		addImmunizationRecordFrame.setBounds(0, 0, 934, 680);
		StudentImmunizationRecordJPanel AS = new StudentImmunizationRecordJPanel(d,foundPerson);
		AS.getTxtStudentID1().setText(text);
		AS.getTxtFirstname().setText(foundPerson.getFirstName());
		AS.getTxtLastname().setText(foundPerson.getLastName());
		AS.setVisible(true);
		addImmunizationRecordFrame.add(AS);
		addImmunizationRecordFrame.setVisible(true);
		}
		
		catch(Exception e) {
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnUpdateRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnImmunizationRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtClassNumber;
    private javax.swing.JTextField txtFather;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtMother;
    private javax.swing.JTextField txtRegisterDate;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentID1;
    private javax.swing.JTextField txtStudentID3;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JTextField getTxtAge() {
		return txtAge;
	}

	public void setTxtAge(javax.swing.JTextField txtAge) {
		this.txtAge = txtAge;
	}

	public javax.swing.JTextField getTxtClassNumber() {
		return txtClassNumber;
	}

	public void setTxtClassNumber(javax.swing.JTextField txtClassNumber) {
		this.txtClassNumber = txtClassNumber;
	}

	public javax.swing.JTextField getTxtFather() {
		return txtFather;
	}

	public void setTxtFather(javax.swing.JTextField txtFather) {
		this.txtFather = txtFather;
	}

	public javax.swing.JTextField getTxtFirstname() {
		return txtFirstname;
	}

	public void setTxtFirstname(javax.swing.JTextField txtFirstname) {
		this.txtFirstname = txtFirstname;
	}

	public javax.swing.JTextField getTxtLastname() {
		return txtLastname;
	}

	public void setTxtLastname(javax.swing.JTextField txtLastname) {
		this.txtLastname = txtLastname;
	}

	public javax.swing.JTextField getTxtMother() {
		return txtMother;
	}

	public void setTxtMother(javax.swing.JTextField txtMother) {
		this.txtMother = txtMother;
	}

	public javax.swing.JTextField getTxtRegisterDate() {
		return txtRegisterDate;
	}

	public void setTxtRegisterDate(javax.swing.JTextField txtRegisterDate) {
		this.txtRegisterDate = txtRegisterDate;
	}

	public javax.swing.JTextField getTxtStudentID() {
		return txtStudentID;
	}

	public void setTxtStudentID(javax.swing.JTextField txtStudentID) {
		this.txtStudentID = txtStudentID;
	}

	public javax.swing.JTextField getTxtStudentID1() {
		return txtStudentID1;
	}

	public void setTxtStudentID1(javax.swing.JTextField txtStudentID1) {
		this.txtStudentID1 = txtStudentID1;
	}

	public javax.swing.JTextField getTxtStudentID3() {
		return txtStudentID3;
	}

	public void setTxtStudentID3(javax.swing.JTextField txtStudentID3) {
		this.txtStudentID3 = txtStudentID3;
	}
    
    
}
